name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install depencies
      run: yarn 
    - name: build docker file
      run: docker build . --file Dockerfile --tag rental:v1
    - name: push to docker hub
      run: docker push emmanuel450666/test-repo1:rental:v1
