name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install depencies
      run: yarn 
    - uses: mr-smithers-excellent/docker-build-push@v5
    - name: Build & push Docker image
      with:
        image: rental
        tags: v1
        registry: registry-url.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
